### PR TITLE
add signup submission button

### LINKED ISSUE #68: User signup page incomplete and missing submit button
User model currently from basic django user model

However, additional fields were meant to be included (#9) :

- email
- ORCID
- GitHub
- twitter

## Current situation

- Currently there is no user model in `reprohack/models.py` or form in `forms.py` 
- There is a `UserCreateView` view in `reprohack/views.py` which is sourcing `from ..users.forms import UserChangeForm, UserCreationForm`. Many lines in the field are commented out. There is also a signup function above the form, unclear what it does.
- `UserCreationForm` is in  `users/forms.py`
- `User` model in `users/models.py` but no additional fields added

### PR DESCRIPTION
**Pull request by annakrystalli**
### Summary

Partially addresses #68 

Adds a signup button and saves basic user form

### CODE REVIEW

**Comment by annakrystalli** [comment]
Linter throwing an error again. Going to ignore as tests pass

**Comment by willfurnass** [comment]
@annakrystalli Linting err fixed.

**Comment by annakrystalli** [comment]
Oh no...I can't push now 😭

**Comment by annakrystalli** [comment]
OK fixed branch

**Pull request merged**
